# Generated by Django 4.0.4 on 2022-05-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procutos',
            old_name='nanme',
            new_name='name',
        ),
    ]
