# Generated by Django 4.0.4 on 2022-05-29 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_procutos_sku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procutos',
            new_name='Productos',
        ),
    ]
