# Generated by Django 4.0.4 on 2022-06-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_productos_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='new_price',
            field=models.IntegerField(null=True),
        ),
    ]
